services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data/sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql
    networks:
      - invnet

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://inventory_user:inventory_pass@db:5432/inventory_db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - invnet

networks:
  invnet:
